# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  namespace: default
spec:
  ingressClassName: "nginx"
  rules:
  - host: rabbitmq-manager.com
    http:
      paths:
      - path: /
        pathType: Prefix        
        backend:
          service:
            name: rabbitmq-service
            port:
              number: 15672
---

