# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: "pod-1"
  namespace: namespace-1 
  labels:
    app: "pod-1"
spec:
  containers:
  - name: pod-1
    image: "nginx:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort: 80
      name:  http
  restartPolicy: Always
---

